/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, Emphasis, Size } from "./components/types";
export { Color, Emphasis, Size } from "./components/types";
export namespace Components {
    interface DyneButton {
        /**
          * button color could be: 'primary', 'secondary' or 'tertiary' or even 'neutral'
         */
        "color"?: Color;
        /**
          * button emphasis could be: 'low', 'medium', 'high'
         */
        "emphasis"?: Emphasis;
        /**
          * button sizes are s, m, l
         */
        "size"?: Size;
    }
}
declare global {
    interface HTMLDyneButtonElement extends Components.DyneButton, HTMLStencilElement {
    }
    var HTMLDyneButtonElement: {
        prototype: HTMLDyneButtonElement;
        new (): HTMLDyneButtonElement;
    };
    interface HTMLElementTagNameMap {
        "dyne-button": HTMLDyneButtonElement;
    }
}
declare namespace LocalJSX {
    interface DyneButton {
        /**
          * button color could be: 'primary', 'secondary' or 'tertiary' or even 'neutral'
         */
        "color"?: Color;
        /**
          * button emphasis could be: 'low', 'medium', 'high'
         */
        "emphasis"?: Emphasis;
        /**
          * button sizes are s, m, l
         */
        "size"?: Size;
    }
    interface IntrinsicElements {
        "dyne-button": DyneButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dyne-button": LocalJSX.DyneButton & JSXBase.HTMLAttributes<HTMLDyneButtonElement>;
        }
    }
}
