/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, Emphasis, Size } from "./components/types";
export { Color, Emphasis, Size } from "./components/types";
export namespace Components {
    interface DyneButton {
        /**
          * button color could be: 'primary', 'secondary' or 'tertiary'
         */
        "color"?: Color;
        /**
          * button emphasis could be: 'slight', 'moderate' or 'high'
         */
        "emphasis"?: Emphasis;
        /**
          * button sizes could be: 'small', 'medium' or 'large'
         */
        "size"?: Size;
    }
    interface DyneInline {
        "gap"?: number;
    }
}
declare global {
    interface HTMLDyneButtonElement extends Components.DyneButton, HTMLStencilElement {
    }
    var HTMLDyneButtonElement: {
        prototype: HTMLDyneButtonElement;
        new (): HTMLDyneButtonElement;
    };
    interface HTMLDyneInlineElement extends Components.DyneInline, HTMLStencilElement {
    }
    var HTMLDyneInlineElement: {
        prototype: HTMLDyneInlineElement;
        new (): HTMLDyneInlineElement;
    };
    interface HTMLElementTagNameMap {
        "dyne-button": HTMLDyneButtonElement;
        "dyne-inline": HTMLDyneInlineElement;
    }
}
declare namespace LocalJSX {
    interface DyneButton {
        /**
          * button color could be: 'primary', 'secondary' or 'tertiary'
         */
        "color"?: Color;
        /**
          * button emphasis could be: 'slight', 'moderate' or 'high'
         */
        "emphasis"?: Emphasis;
        /**
          * button sizes could be: 'small', 'medium' or 'large'
         */
        "size"?: Size;
    }
    interface DyneInline {
        "gap"?: number;
    }
    interface IntrinsicElements {
        "dyne-button": DyneButton;
        "dyne-inline": DyneInline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dyne-button": LocalJSX.DyneButton & JSXBase.HTMLAttributes<HTMLDyneButtonElement>;
            "dyne-inline": LocalJSX.DyneInline & JSXBase.HTMLAttributes<HTMLDyneInlineElement>;
        }
    }
}
